/* resource.H,v 1.3 2002/01/05 19:28:19 root Exp */

// Resource ids for windows, dialogs and notebooks

#define DLG_NOTEBOOK 269
#define NBK_NOTEBOOK 261
#define NBKP_NOTEBOOK1 270
// #define ST_TEXT1 271
// #define ST_TEXT2 273

#define NBKP_NOTEBOOK4 275
#define ST_TEXT4 276

#define NBKP_NOTEBOOK5 277
#define ST_TEXT5 278
#define NBKP_NOTEBOOK7 281
#define ST_TEXT7 282
#define NBKP_NOTEBOOK8 283
#define ST_TEXT8 284
#define NBKP_NOTEBOOK9 285
#define ST_TEXT9 286

#define PB_UNDO 262
#define PB_DEFAULT 263
#define PB_HELP 264
#define CKB_VALIDATIONERROR 279

#include "priority.h"
#include "rego.h"
#include "multi.h"
#include "out.h"
#include "dlg_log.h"
#include "filter.h"
#include "post.h"
#include "user.h"
#include "dlg_socks.h"



